use crate::*;

pub(crate) fn cargo_toml_content(
    db: &dyn RustCodeGenQueryGroup,
    main_file: FilePtr,
) -> Arc<String> {
    let package = db.package(main_file).unwrap();
    let package_ident = package.ident;
    msg_once!("ad hoc");
    let husky_dir_rel = "../../..";
    Arc::new(format!(
        r#"[package]
name = "{package_ident}"
version = "0.0.0"
description = "generated by husky compiler"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.56"

[dependencies]
tokio = {{ version = "1.16.1", features = ["full"] }}
husky-debugger = {{ path = "{husky_dir_rel}/core/crates/apps/husky-debugger", version = "0.0.0" }}
husky-compile-time = {{ path = "{husky_dir_rel}/core/crates/compile/husky-compile-time", version = "0.0.0" }}
__husky_root = {{ path = "{husky_dir_rel}/core/crates/static/__husky_root", version = "0.0.0" }}


[[bin]]
name = "{package_ident}-debugger"
path = "src/bin/main.rs"
"#
    ))
}
