#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EntityClass {
    Module,
    Type,
    FunctionFn,
    FunctionGn,
    TypeAlias,
    Val,
    Trait,
    TypeVariant,
    MethodFn,
    MethodGn,
    AssocFunctionFn,
    AssocFunctionGn,
    MemoizedField,
    AssocVal,
    AssocType,
    ImplBlock,
    Attr,
    Formal,
    AssocFormal,
    Const,
}
