//! As we expect Lean in our projects to be autogenerated by visored, we group defns into arena for convenience
pub mod def;
pub mod variable;

use crate::*;
use idx_arena::{Arena, ArenaIdx, ArenaIdxRange, ArenaRef};

pub enum LnItemDefnData {}

pub type LnItemDefnArena = Arena<LnItemDefnData>;
pub type LnItemDefnArenaRef<'a> = ArenaRef<'a, LnItemDefnData>;
pub type LnItemDefnIdx = ArenaIdx<LnItemDefnData>;
pub type LnItemDefnIdxRange = ArenaIdxRange<LnItemDefnData>;
