// this is generated by husky_vm_interface_code_gen::rust_code::write_rust_code
// do not modify by hand

use crate::*;

type void = ();
type b32 = u32;
type b64 = u64;

// VirtualStruct
#[no_mangle]
pub unsafe extern "C" fn __virtual_struct_clone(data: *mut ()) -> *mut () {
    Box::<VirtualStruct>::into_raw(Box::new((*(data as *mut VirtualStruct)).clone())) as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __virtual_struct_drop(data: *mut ()) {
    Box::from_raw(data as *mut VirtualStruct);
}
#[no_mangle]
pub unsafe extern "C" fn __virtual_struct_eq(this: &(), other: &()) -> bool {
    *(this as *const () as *const VirtualStruct) == *(other as *const () as *const VirtualStruct)
}
#[no_mangle]
pub unsafe extern "C" fn __virtual_struct_assign(registers: *mut __Register) {
    let registers = std::slice::from_raw_parts_mut(registers, 2);
    *registers[0].downcast_temp_mut::<VirtualStruct>() = registers[1].downcast_move()
}
#[no_mangle]
pub static __VIRTUAL_STRUCT_VTABLE: __RegisterVTable = __RegisterVTable {
    primitive_value_to_bool: None,
    primitive_value_to_box: None,
    clone: __virtual_struct_clone,
    drop: __virtual_struct_drop,
    eq: __virtual_struct_eq,
    assign: __virtual_struct_assign,
    typename_str: "VirtualStruct",
};

// VirtualVec
#[no_mangle]
pub unsafe extern "C" fn __virtual_vec_clone(data: *mut ()) -> *mut () {
    Box::<VirtualVec>::into_raw(Box::new((*(data as *mut VirtualVec)).clone())) as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __virtual_vec_drop(data: *mut ()) {
    Box::from_raw(data as *mut VirtualVec);
}
#[no_mangle]
pub unsafe extern "C" fn __virtual_vec_eq(this: &(), other: &()) -> bool {
    *(this as *const () as *const VirtualVec) == *(other as *const () as *const VirtualVec)
}
#[no_mangle]
pub unsafe extern "C" fn __virtual_vec_assign(registers: *mut __Register) {
    let registers = std::slice::from_raw_parts_mut(registers, 2);
    *registers[0].downcast_temp_mut::<VirtualVec>() = registers[1].downcast_move()
}
#[no_mangle]
pub static __VIRTUAL_VEC_VTABLE: __RegisterVTable = __RegisterVTable {
    primitive_value_to_bool: None,
    primitive_value_to_box: None,
    clone: __virtual_vec_clone,
    drop: __virtual_vec_drop,
    eq: __virtual_vec_eq,
    assign: __virtual_vec_assign,
    typename_str: "VirtualVec",
};

// VirtualCyclicSlice
#[no_mangle]
pub unsafe extern "C" fn __virtual_cyclic_slice_clone(data: *mut ()) -> *mut () {
    Box::<VirtualCyclicSlice>::into_raw(Box::new((*(data as *mut VirtualCyclicSlice)).clone())) as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __virtual_cyclic_slice_drop(data: *mut ()) {
    Box::from_raw(data as *mut VirtualCyclicSlice);
}
#[no_mangle]
pub unsafe extern "C" fn __virtual_cyclic_slice_eq(this: &(), other: &()) -> bool {
    *(this as *const () as *const VirtualCyclicSlice) == *(other as *const () as *const VirtualCyclicSlice)
}
#[no_mangle]
pub unsafe extern "C" fn __virtual_cyclic_slice_assign(registers: *mut __Register) {
    let registers = std::slice::from_raw_parts_mut(registers, 2);
    *registers[0].downcast_temp_mut::<VirtualCyclicSlice>() = registers[1].downcast_move()
}
#[no_mangle]
pub static __VIRTUAL_CYCLIC_SLICE_VTABLE: __RegisterVTable = __RegisterVTable {
    primitive_value_to_bool: None,
    primitive_value_to_box: None,
    clone: __virtual_cyclic_slice_clone,
    drop: __virtual_cyclic_slice_drop,
    eq: __virtual_cyclic_slice_eq,
    assign: __virtual_cyclic_slice_assign,
    typename_str: "VirtualCyclicSlice",
};
