use crate::*;

pub(crate) fn cargo_toml_content(db: &dyn RustGenQueryGroup, main_file: FilePtr) -> Arc<String> {
    let pack = db.pack(main_file).unwrap();
    Arc::new(format!(
        r#"[pack]
name = "{}"
version = "0.0.0"
description = "generated by husky compiler"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.56"

[dependencies]
tokio = {{ version = "0.2", features = ["full"] }}
husky-lang-debugger = {{ path = "/home/xiyuzhai/Documents/husky/crates/apps/debugger", version = "0.0.0" }}
compile-time-db = {{ path = "/home/xiyuzhai/Documents/husky/crates/compile-time/db", version = "0.0.0" }}
"#,
        &pack.ident // pack name
    ))
}
