// this is generated by husky_datasets_static_defn_code_gen::c_header::write_c_header
// do not modify by hand
#pragma once
#include "husky_vm_interface.h"

// VirtualStruct
extern void *__virtual_struct_clone(void const*);
extern void __virtual_struct_drop(void const*);
extern bool __virtual_struct_eq(void const*, void const*);
extern void __virtual_struct_assign(__Register*);
extern const __RegisterVTable __VIRTUAL_STRUCT_VTABLE;
        
// VirtualEnum
extern void *__virtual_enum_clone(void const*);
extern void __virtual_enum_drop(void const*);
extern bool __virtual_enum_eq(void const*, void const*);
extern void __virtual_enum_assign(__Register*);
extern const __RegisterVTable __VIRTUAL_ENUM_VTABLE;
        
// VirtualVec
extern void *__virtual_vec_clone(void const*);
extern void __virtual_vec_drop(void const*);
extern bool __virtual_vec_eq(void const*, void const*);
extern void __virtual_vec_assign(__Register*);
extern const __RegisterVTable __VIRTUAL_VEC_VTABLE;
        
// VirtualCyclicSlice
extern void *__virtual_cyclic_slice_clone(void const*);
extern void __virtual_cyclic_slice_drop(void const*);
extern bool __virtual_cyclic_slice_eq(void const*, void const*);
extern void __virtual_cyclic_slice_assign(__Register*);
extern const __RegisterVTable __VIRTUAL_CYCLIC_SLICE_VTABLE;
        