use husky_c_code_repr::{CPrimitiveTypeRegistrationHeader, CPrimitiveTypeRegistrationSource};

use super::PRIMITIVE_TYPES;
use crate::NONPRIMITIVE_BUILTIN_TYPES;
use std;
use std::fs::File;
use std::io::prelude::*;

pub fn write_c_header(c_header_path: &str) -> std::io::Result<()> {
    eprintln!("c_header_path: {}", c_header_path);
    let mut buffer = File::create(c_header_path).unwrap();
    write!(
        buffer,
        r#"// this is generated by husky_vm_interface_code_gen::c_header::write_c_header
// do not modify by hand
        
#pragma once
#include <stdbool.h>
#include <stdint.h>

typedef struct unit {{
}} unit;
typedef union __RegisterData {{
    unit as_void;
    bool as_bool;
    int32_t as_i32;
    int64_t as_i64;
    uint32_t as_b32;
    uint64_t as_b64;
    float as_f32;
    double as_f64;
    void *as_opt_ptr;
}} __RegisterData;

typedef bool (*__primitive_value_to_bool_t)(__RegisterData);

typedef void *(*__primitive_value_to_box_t)(__RegisterData);

typedef void (*__drop_t)(void *);

typedef struct __RegisterVTable {{
    char const *typename_str;
    __primitive_value_to_bool_t primitive_value_to_bool;
    __primitive_value_to_box_t primitive_value_to_box;
    __drop_t drop;
}} __RegisterVTable;
    
// handles of primitive types are provided by Rust
"#
    )?;
    for ty in PRIMITIVE_TYPES {
        write!(buffer, "{}", CPrimitiveTypeRegistrationHeader { ty })?
    }
    for ty in NONPRIMITIVE_BUILTIN_TYPES {
        write!(buffer, "{}", CPrimitiveTypeRegistrationSource { ty })?
    }
    Ok(())
}
