[package]
name = "husky-comptime"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.56"

[lib]
doctest = false

[dependencies]
# external
rustc-hash = "1.1.0"
either = "1.6.1"
itertools = "0.10.0"
arrayvec = "0.7"
indexmap = "1.7"
salsa = "0.17.0-pre.2"
# abstraction
upcast = { path = "../../abstraction/upcast" }
fold = { path = "../../abstraction/fold" }
# utils
husky-check-utils = { path = "../../utils/husky-check-utils" }
husky-dev-utils = { path = "../../utils/husky-dev-utils" }
husky-print-utils = { path = "../../utils/husky-print-utils" }
sync-utils = { path = "../../utils/husky-sync-utils" }
husky-test-utils = { path = "../../utils/husky-test-utils" }
# syntax
husky-file = { path = "../../syntax/husky-file" }
husky-word = { path = "../../kernel/husky-word" }
husky-token = { path = "../../syntax/husky-token" }
husky-entity-route = { path = "../../kernel/husky-entity-route" }
husky-entity-syntax = { path = "../../syntax/husky-entity-syntax" }
husky-text = { path = "../../syntax/husky-text" }
husky-ast = { path = "../../syntax/husky-ast" }
husky-fmt = { path = "../../syntax/husky-fmt" }
husky-entity-kind = { path = "../../syntax/husky-entity-kind" }
husky-atom = { path = "../../syntax/husky-atom" }
# infer
infer-decl = { path = "../../infer/husky-infer-decl" }
husky-infer-entity-route = { path = "../../infer/husky-infer-entity-route" }
infer-contract = { path = "../../infer/husky-infer-contract" }
husky-infer-qualified-ty = { path = "../../infer/husky-infer-qualified-ty" }
infer-total = { path = "../../infer/total" }
# semantics
husky-entity-semantics = { path = "../../semantics/husky-entity-semantics" }
husky-lazy-semantics = { path = "../../semantics/husky-lazy-semantics" }
husky-package-semantics = { path = "../../semantics/husky-package-semantics" }
# ide
husky-hover = { path = "../../ide/husky-hover" }
husky-completion = { path = "../../ide/husky-completion" }
husky-diagnostics = { path = "../../ide/husky-diagnostics" }
# comptime
husky-layout = { path = "../../comptime/husky-layout" }
husky-linkage-table = { path = "../../comptime/husky-linkage-table" }
husky-rust-code-gen = { path = "../../comptime/husky-rust-code-gen" }
# vm
husky-vm = { path = "../../vm/husky-vm" }
# devtime
husky-trace-protocol = { path = "../../devtime/husky-trace-protocol" }
# static
husky-static-defn = { path = "../../static/husky-static-defn" }
__husky = { path = "../../static/__husky" }
# forks
thin-vec = { path = "../../../forks/thin-vec" }
