use crate::*;

pub(crate) fn cargo_toml_content(db: &dyn RustGenQueryGroup, main_file: FilePtr) -> Arc<String> {
    let pack = db.package(main_file).unwrap();
    Arc::new(format!(
        r#"[package]
name = "{}"
version = "0.0.0"
description = "generated by husky compiler"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.56"

[dependencies]
tokio = {{ version = "0.2", features = ["full"] }}
husky-tracer = {{ path = "../../crates/apps/debugger", version = "0.0.0" }}
husky-compile-time = {{ path = "../../crates/compile/husky-compile-time", version = "0.0.0" }}


[[bin]]
name = "{}-debugger"
path = "src/bin/main.rs"
"#,
        &pack.ident, &pack.ident
    ))
}
