mod tests;

use crate::src::MayuriSrc;

use self::tests::MayuriTestSubject;
use husky_config_utils::IsConfig;
use serde::Deserialize;
use std::env;
use std::fs;
use std::io;
use std::path::PathBuf;
use tests::MayuriTestSubjects;

#[derive(Debug)]
pub struct MayuriFs {
    root: PathBuf,
    src: MayuriSrc,
    test_subjects: MayuriTestSubjects,
    /// read from `<root>/Mayuri.toml`
    mayuri_config: MayuriConfig,
    /// read from `<root>/Nemu.toml`
    nemu_config: NemuConfig,
}

#[derive(Debug, Deserialize)]
pub struct MayuriConfig {
    // Add fields as needed
}

#[derive(Debug, Deserialize)]
pub struct NemuConfig {
    // Add fields as needed
}

impl MayuriFs {
    pub fn new(root: PathBuf) -> io::Result<Self> {
        let mayuri_config = MayuriConfig::read_from_toml_file(&root.join("Mayuri.toml"))?;
        let nemu_config = NemuConfig::read_from_toml_file(&root.join("Nemu.toml"))?;
        let src = MayuriSrc::new(root.join("src"), &["py"])?;
        let test_subjects = MayuriTestSubjects::from_dir(root.join("tests"), &src);
        Ok(MayuriFs {
            root,
            src,
            mayuri_config,
            nemu_config,
            test_subjects,
        })
    }
}

#[test]
fn mayuri_fs_works() {
    use husky_path_utils::HuskyLangDevPaths;
    use std::env;
    use std::path::Path;

    let dev_paths = HuskyLangDevPaths::new();
    let root = dev_paths.root();

    // Change the current working directory to the root
    env::set_current_dir(&root).unwrap();

    // Use a relative path from the root
    let mayuri_prototype_dir = Path::new("experiments/mayuri-prototype");

    // Now the current directory is the root, so we use the relative path
    let fs = MayuriFs::new(mayuri_prototype_dir.to_path_buf()).unwrap();
    expect_test::expect![[r#"
        MayuriFs {
            root: "experiments/mayuri-prototype",
            src: MayuriSrc {
                dir_path: "experiments/mayuri-prototype/src",
                shas: {
                    "main.py": Sha512Output(
                        [
                            124,
                            191,
                            9,
                            89,
                            223,
                            51,
                            148,
                            1,
                            201,
                            0,
                            35,
                            243,
                            147,
                            140,
                            215,
                            214,
                            33,
                            146,
                            112,
                            134,
                            53,
                            97,
                            4,
                            236,
                            102,
                            201,
                            204,
                            2,
                            62,
                            162,
                            99,
                            171,
                            33,
                            2,
                            234,
                            121,
                            171,
                            230,
                            230,
                            210,
                            74,
                            105,
                            60,
                            168,
                            194,
                            44,
                            180,
                            41,
                            168,
                            201,
                            230,
                            85,
                            88,
                            179,
                            208,
                            97,
                            59,
                            240,
                            97,
                            59,
                            49,
                            233,
                            208,
                            97,
                        ],
                    ),
                    "datasets/gaussian.py": Sha512Output(
                        [
                            229,
                            14,
                            149,
                            235,
                            242,
                            241,
                            241,
                            33,
                            13,
                            83,
                            168,
                            71,
                            83,
                            231,
                            56,
                            143,
                            127,
                            107,
                            161,
                            234,
                            112,
                            42,
                            177,
                            157,
                            30,
                            152,
                            58,
                            130,
                            172,
                            221,
                            32,
                            216,
                            117,
                            98,
                            215,
                            235,
                            226,
                            28,
                            14,
                            43,
                            111,
                            127,
                            51,
                            137,
                            105,
                            8,
                            84,
                            151,
                            222,
                            241,
                            81,
                            7,
                            200,
                            1,
                            130,
                            179,
                            156,
                            38,
                            228,
                            245,
                            22,
                            166,
                            30,
                            219,
                        ],
                    ),
                    "models/fcn.py": Sha512Output(
                        [
                            27,
                            116,
                            9,
                            204,
                            240,
                            213,
                            163,
                            77,
                            58,
                            119,
                            234,
                            171,
                            250,
                            159,
                            226,
                            116,
                            39,
                            101,
                            91,
                            233,
                            41,
                            113,
                            39,
                            238,
                            149,
                            34,
                            170,
                            27,
                            244,
                            4,
                            109,
                            79,
                            148,
                            89,
                            131,
                            103,
                            129,
                            105,
                            203,
                            26,
                            115,
                            72,
                            237,
                            202,
                            196,
                            126,
                            240,
                            217,
                            226,
                            201,
                            36,
                            19,
                            14,
                            91,
                            204,
                            95,
                            13,
                            148,
                            147,
                            120,
                            82,
                            196,
                            47,
                            27,
                        ],
                    ),
                    "visualize.py": Sha512Output(
                        [
                            150,
                            127,
                            239,
                            147,
                            123,
                            98,
                            212,
                            62,
                            163,
                            239,
                            148,
                            222,
                            44,
                            43,
                            28,
                            52,
                            177,
                            2,
                            86,
                            61,
                            65,
                            178,
                            129,
                            246,
                            116,
                            155,
                            41,
                            102,
                            2,
                            37,
                            222,
                            79,
                            45,
                            242,
                            37,
                            19,
                            126,
                            84,
                            134,
                            69,
                            68,
                            245,
                            149,
                            38,
                            189,
                            119,
                            100,
                            27,
                            164,
                            2,
                            73,
                            247,
                            173,
                            96,
                            213,
                            132,
                            64,
                            1,
                            201,
                            112,
                            3,
                            49,
                            234,
                            78,
                        ],
                    ),
                    "datasets/ring.py": Sha512Output(
                        [
                            27,
                            116,
                            9,
                            204,
                            240,
                            213,
                            163,
                            77,
                            58,
                            119,
                            234,
                            171,
                            250,
                            159,
                            226,
                            116,
                            39,
                            101,
                            91,
                            233,
                            41,
                            113,
                            39,
                            238,
                            149,
                            34,
                            170,
                            27,
                            244,
                            4,
                            109,
                            79,
                            148,
                            89,
                            131,
                            103,
                            129,
                            105,
                            203,
                            26,
                            115,
                            72,
                            237,
                            202,
                            196,
                            126,
                            240,
                            217,
                            226,
                            201,
                            36,
                            19,
                            14,
                            91,
                            204,
                            95,
                            13,
                            148,
                            147,
                            120,
                            82,
                            196,
                            47,
                            27,
                        ],
                    ),
                },
            },
            test_subjects: MayuriTestSubjects {
                subjects: [
                    MayuriTestSubject {
                        path: "experiments/mayuri-prototype/tests/hello.yml",
                        rank: 0,
                        experiment: Experiment {
                            src: [
                                (
                                    ExperimentSrcDestinationPath {
                                        relative_path: "dataset.py",
                                    },
                                    ExperimentSrcOrigin {
                                        relative_path: "datasets/gaussian.py",
                                        content_sha: Sha512Output(
                                            [
                                                229,
                                                14,
                                                149,
                                                235,
                                                242,
                                                241,
                                                241,
                                                33,
                                                13,
                                                83,
                                                168,
                                                71,
                                                83,
                                                231,
                                                56,
                                                143,
                                                127,
                                                107,
                                                161,
                                                234,
                                                112,
                                                42,
                                                177,
                                                157,
                                                30,
                                                152,
                                                58,
                                                130,
                                                172,
                                                221,
                                                32,
                                                216,
                                                117,
                                                98,
                                                215,
                                                235,
                                                226,
                                                28,
                                                14,
                                                43,
                                                111,
                                                127,
                                                51,
                                                137,
                                                105,
                                                8,
                                                84,
                                                151,
                                                222,
                                                241,
                                                81,
                                                7,
                                                200,
                                                1,
                                                130,
                                                179,
                                                156,
                                                38,
                                                228,
                                                245,
                                                22,
                                                166,
                                                30,
                                                219,
                                            ],
                                        ),
                                    },
                                ),
                                (
                                    ExperimentSrcDestinationPath {
                                        relative_path: "model.py",
                                    },
                                    ExperimentSrcOrigin {
                                        relative_path: "models/fcn.py",
                                        content_sha: Sha512Output(
                                            [
                                                27,
                                                116,
                                                9,
                                                204,
                                                240,
                                                213,
                                                163,
                                                77,
                                                58,
                                                119,
                                                234,
                                                171,
                                                250,
                                                159,
                                                226,
                                                116,
                                                39,
                                                101,
                                                91,
                                                233,
                                                41,
                                                113,
                                                39,
                                                238,
                                                149,
                                                34,
                                                170,
                                                27,
                                                244,
                                                4,
                                                109,
                                                79,
                                                148,
                                                89,
                                                131,
                                                103,
                                                129,
                                                105,
                                                203,
                                                26,
                                                115,
                                                72,
                                                237,
                                                202,
                                                196,
                                                126,
                                                240,
                                                217,
                                                226,
                                                201,
                                                36,
                                                19,
                                                14,
                                                91,
                                                204,
                                                95,
                                                13,
                                                148,
                                                147,
                                                120,
                                                82,
                                                196,
                                                47,
                                                27,
                                            ],
                                        ),
                                    },
                                ),
                            ],
                            config: OrderedYaml("---
                            epochs: 10"),
                        },
                    },
                    MayuriTestSubject {
                        path: "experiments/mayuri-prototype/tests/hello.yml",
                        rank: 1,
                        experiment: Experiment {
                            src: [
                                (
                                    ExperimentSrcDestinationPath {
                                        relative_path: "dataset.py",
                                    },
                                    ExperimentSrcOrigin {
                                        relative_path: "datasets/ring.py",
                                        content_sha: Sha512Output(
                                            [
                                                27,
                                                116,
                                                9,
                                                204,
                                                240,
                                                213,
                                                163,
                                                77,
                                                58,
                                                119,
                                                234,
                                                171,
                                                250,
                                                159,
                                                226,
                                                116,
                                                39,
                                                101,
                                                91,
                                                233,
                                                41,
                                                113,
                                                39,
                                                238,
                                                149,
                                                34,
                                                170,
                                                27,
                                                244,
                                                4,
                                                109,
                                                79,
                                                148,
                                                89,
                                                131,
                                                103,
                                                129,
                                                105,
                                                203,
                                                26,
                                                115,
                                                72,
                                                237,
                                                202,
                                                196,
                                                126,
                                                240,
                                                217,
                                                226,
                                                201,
                                                36,
                                                19,
                                                14,
                                                91,
                                                204,
                                                95,
                                                13,
                                                148,
                                                147,
                                                120,
                                                82,
                                                196,
                                                47,
                                                27,
                                            ],
                                        ),
                                    },
                                ),
                                (
                                    ExperimentSrcDestinationPath {
                                        relative_path: "model.py",
                                    },
                                    ExperimentSrcOrigin {
                                        relative_path: "models/fcn.py",
                                        content_sha: Sha512Output(
                                            [
                                                27,
                                                116,
                                                9,
                                                204,
                                                240,
                                                213,
                                                163,
                                                77,
                                                58,
                                                119,
                                                234,
                                                171,
                                                250,
                                                159,
                                                226,
                                                116,
                                                39,
                                                101,
                                                91,
                                                233,
                                                41,
                                                113,
                                                39,
                                                238,
                                                149,
                                                34,
                                                170,
                                                27,
                                                244,
                                                4,
                                                109,
                                                79,
                                                148,
                                                89,
                                                131,
                                                103,
                                                129,
                                                105,
                                                203,
                                                26,
                                                115,
                                                72,
                                                237,
                                                202,
                                                196,
                                                126,
                                                240,
                                                217,
                                                226,
                                                201,
                                                36,
                                                19,
                                                14,
                                                91,
                                                204,
                                                95,
                                                13,
                                                148,
                                                147,
                                                120,
                                                82,
                                                196,
                                                47,
                                                27,
                                            ],
                                        ),
                                    },
                                ),
                            ],
                            config: OrderedYaml("---
                            epochs: 10"),
                        },
                    },
                ],
            },
            mayuri_config: MayuriConfig,
            nemu_config: NemuConfig,
        }
    "#]]
    .assert_debug_eq(&fs);
}
