use husky_core::*;
use ad_hoc_task_dependency::*;
use mnist_classifier::*;

#[rustfmt::skip]
linkage_impls![
    ConnectedComponentDistribution::__constructor,
    EffHoles::__constructor,
    hole_tmpl,
    ConnectedComponent::__constructor,
    horizontal_extend,
    find_connected_components,
    <ConnectedComponent as Visualize>::visualize,
    ConnectedComponent::top_k_row_span_sum,
    ConnectedComponent::top_k_row_right_mass_sum,
    RawContour::__constructor,
    get_pixel_pair,
    get_pixel_to_the_left,
    get_pixel_to_the_right,
    get_inward_direction,
    get_angle_change,
    get_outward_direction,
    StreakCache::__constructor,
    get_concave_middle_point,
    find_raw_contours,
    <RawContour as Visualize>::visualize,
    RawContour::displacement,
    Point2d::__constructor,
    RelativePoint2d::__constructor,
    Vector2d::__constructor,
    ClosedRange::__constructor,
    BoundingBox::__constructor,
    RelativeBoundingBox::__constructor,
    Point2d::from_i_shift28,
    Point2d::vector,
    Point2d::to,
    Point2d::norm,
    Point2d::dist,
    Vector2d::point,
    Vector2d::to,
    Vector2d::norm,
    Vector2d::dot,
    Vector2d::cross,
    Vector2d::angle,
    Vector2d::rotation_direction_to,
    Vector2d::angle_to,
    ClosedRange::relative_range,
    ClosedRange::relative_point,
    BoundingBox::relative_bounding_box,
    BoundingBox::relative_point,
    BoundingBox::xmin,
    BoundingBox::xmax,
    BoundingBox::ymin,
    BoundingBox::ymax,
    RelativeBoundingBox::xmin,
    RelativeBoundingBox::xmax,
    RelativeBoundingBox::ymin,
    RelativeBoundingBox::ymax,
    LineSegmentStroke::__constructor,
    LineSegmentSketch::__constructor,
    go_right,
    go_left,
    extend_end,
    extend_start,
    find_line_segments,
    <LineSegmentStroke as Visualize>::visualize,
    LineSegmentStroke::new,
    LineSegmentStroke::displacement,
    <LineSegmentSketch as Visualize>::visualize,
    LineSegmentSketch::new,
    ConcaveComponent::__constructor,
    find_concave_components,
    <ConcaveComponent as Visualize>::visualize,
    ConcaveComponent::line_segment,
    ConcaveComponent::start,
    ConcaveComponent::end,
    ConcaveComponent::displacement,
    ConcaveComponent::start_tangent,
    ConcaveComponent::end_tangent,
    ConvexComponent::__constructor,
    <ConvexComponent as Visualize>::visualize,
    is_convex,
    LineSegment::__constructor,
    LineSegment::displacement,
    LineSegment::dist_to_point,
    FermiMatchResult::__constructor,
    fermi_match,
    almost_closed,
    upmost,
    downmost,
    hat,
    upmost,
    bottom1,
    uparc,
    downarc,
    back,
    left_coordinate_max,
    displacement_downwards,
    cc_box_heights,
    simple_leftdown_pattern,
    leftupcc_pattern,
    leftdowncc_pattern,
    big_mouth,
    downmost,
    big_cc,
    left_cc_pattern,
    right_cc_pattern,
    down_cc_pattern,
    <todo!() as Clone>::clone,
    Vec::push,
    Vec::ilen,
    Vec::last,
    Vec::push,
    Vec::pop,
    Vec::push,
    CyclicSlice::first,
    <todo!() as Clone>::clone,
    CyclicSlice::last,
    Vec::ilen,
    Vec::last,
    CyclicSlice::start,
    Vec::pop,
    CyclicSlice::end,
    Vec::push,
    Vec::first,
    Vec::cyclic_slice_leashed,
    <todo!() as Visualize>::visualize,
    Vec::cyclic_slice_leashed,
    Vec::push,
    <todo!() as Visualize>::visualize,
    CyclicSlice::first,
    CyclicSlice::last,
    Vec::collect_leashes,
    Vec::ilen,
    Vec::pop_with_largest_opt_f32,
    Vec::push,
];