#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EntityKindProtocol {
    Module,
    Type,
    FunctionFn,
    FunctionGn,
    AliasType,
    Val,
    Trait,
    TypeVariant,
    MethodFn,
    MethodGn,
    AssociatedFunctionFn,
    AssociatedFunctionGn,
    MemoizedField,
    AssociatedVal,
    AssociatedType,
    ImplBlock,
    Attr,
}
