pub mod zero;
pub mod one;
pub mod six;
pub mod three;
pub mod four;
pub mod five;
pub mod seven;
pub mod eight;
pub mod nine;
pub mod two;

use self::zero::*;
use self::one::*;
use self::six::*;
use self::three::*;
use self::four::*;
use self::five::*;
use self::seven::*;
use self::eight::*;
use self::nine::*;
use self::two::*;