#[cfg(feature = "allow-print")]
pub const RESET: &str = "\x1B[0m";
#[cfg(not(feature = "allow-print"))]
pub const RESET: &str = "";
pub const BLACK: &str = "\x1B[30m";
pub const RED: &str = "\x1B[31m";
#[cfg(feature = "allow-print")]
pub const GREEN: &str = "\x1B[32m";
#[cfg(not(feature = "allow-print"))]
pub const GREEN: &str = "";
#[cfg(feature = "allow-print")]
pub const BRIGHT_GREEN: &str = "\x1B[38;2;150;255;150m";
#[cfg(not(feature = "allow-print"))]
pub const BRIGHT_GREEN: &str = "";
#[cfg(feature = "allow-print")]
pub const LIGHT_YELLOW: &str = "\x1B[38;2;230;200;180m";
#[cfg(not(feature = "allow-print"))]
pub const LIGHT_YELLOW: &str = "";
#[cfg(feature = "allow-print")]
pub const YELLOW: &str = "\x1B[38;2;220;180;55m";
#[cfg(not(feature = "allow-print"))]
pub const YELLOW: &str = "";
#[cfg(feature = "allow-print")]
pub const BLUE: &str = "\x1B[34m";
#[cfg(not(feature = "allow-print"))]
pub const BLUE: &str = "";
#[cfg(feature = "allow-print")]
pub const MAGENTA: &str = "\x1B[35m";
#[cfg(not(feature = "allow-print"))]
pub const MAGENTA: &str = "";
#[cfg(feature = "allow-print")]
pub const CYAN: &str = "\x1B[36m";
#[cfg(not(feature = "allow-print"))]
pub const CYAN: &str = "";
#[cfg(feature = "allow-print")]
pub const WHITE: &str = "\x1B[37m";
#[cfg(not(feature = "allow-print"))]
pub const WHITE: &str = "";
#[cfg(feature = "allow-print")]
pub const BOLDBLACK: &str = "\033[1m\033[30m";
#[cfg(not(feature = "allow-print"))]
pub const BOLDBLACK: &str = "";
#[cfg(feature = "allow-print")]
pub const PINK: &str = "\x1B[38;2;200;50;155m";
#[cfg(not(feature = "allow-print"))]
pub const PINK: &str = "";
