[package]
name = "husky-semantic-token"
version.workspace = true
edition = "2021"

[dependencies]
itertools = "0.11.0"
lsp-types.workspace = true
# abstractions
salsa.workspace = true
# fs
husky-vfs.workspace = true
# lex
husky-text-protocol.workspace = true
husky-token-data = { path = "../../lex/husky-token-data", features = [
    "protocol_support"
] }
husky-token.workspace = true
# ide
husky-token-info = { path = "../../ide/husky-token-info", features = [
    "protocol_support"
] }
# kernel
husky-entity-kind = { path = "../../kernel/husky-entity-kind", features = [
    "protocol_support"
] }
# protocols
husky-entity-protocol = { path = "../../protocols/husky-entity-protocol" }
husky-token-protocol = { path = "../../protocols/husky-token-protocol" }
# semantics
husky-sema-place-contract.workspace = true
# syntax
husky-entity-tree.workspace = true
husky-syn-expr.workspace = true
husky-syn-decl.workspace = true
husky-syn-defn.workspace = true

[dev-dependencies]
# fs
husky-vfs = { workspace = true, features = ["test_utils"] }
# kernel
husky-coword.workspace = true
husky-entity-path.workspace = true
husky-term-prelude.workspace = true
husky-dec-term.workspace = true
husky-dec-ty.workspace = true
husky-eth-term.workspace = true
husky-eth-signature.workspace = true
husky-fly-term.workspace = true
# lex
husky-text.workspace = true
husky-toml-token.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_utils"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-syn-expr.workspace = true
husky-corgi-config-ast.workspace = true
# infer
husky-manifest.workspace = true
husky-dec-signature.workspace = true
husky-sema-expr.workspace = true
husky-corgi-config.workspace = true
husky-semantic-token = { path = ".", features = ["test_utils"] }

[features]
test_utils = ["salsa/test_utils"]
