// this is generated by husky_vm_interface_code_gen::rust_code::write_rust_code
// do not modify by hand

use crate::*;

type void = ();
type b32 = u32;
type b64 = u64;

// void
#[no_mangle]
pub unsafe extern "C" fn __void_primitive_value_to_bool(data: __RegisterData) -> bool {
    let data = data.as_void;
    false
}
#[no_mangle]
pub unsafe extern "C" fn __void_primitive_value_to_box(data: __RegisterData) -> *mut () {
    let data = data.as_void;
    let ptr: *mut void = Box::<void>::into_raw(Box::new(data));
    ptr as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __void_clone(data: *mut ()) -> *mut () {
    Box::<void>::into_raw(Box::new((*(data as *mut void)).clone())) as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __void_drop(data: *mut ()) {
    Box::from_raw(data as *mut void);
}
#[no_mangle]
pub unsafe extern "C" fn __void_eq(this: &(), other: &()) -> bool {
    *(this as *const () as *const void) == *(other as *const () as *const void)
}
extern "C" {
    pub static __VOID_VTABLE: __RegisterVTable;
}
impl<'eval> __Register<'eval> {
    pub fn downcast_void(&self) -> void {
        unsafe {
            assert_eq!(self.vtable as *const _, &__VOID_VTABLE as *const _);
            match self.data_kind {
                __RegisterDataKind::PrimitiveValue => self.data.as_void,
                _ => *(self.data.as_ptr as *const void),
            }
        }
    }
}

// bool
#[no_mangle]
pub unsafe extern "C" fn __bool_primitive_value_to_bool(data: __RegisterData) -> bool {
    let data = data.as_bool;
    data
}
#[no_mangle]
pub unsafe extern "C" fn __bool_primitive_value_to_box(data: __RegisterData) -> *mut () {
    let data = data.as_bool;
    let ptr: *mut bool = Box::<bool>::into_raw(Box::new(data));
    ptr as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __bool_clone(data: *mut ()) -> *mut () {
    Box::<bool>::into_raw(Box::new((*(data as *mut bool)).clone())) as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __bool_drop(data: *mut ()) {
    Box::from_raw(data as *mut bool);
}
#[no_mangle]
pub unsafe extern "C" fn __bool_eq(this: &(), other: &()) -> bool {
    *(this as *const () as *const bool) == *(other as *const () as *const bool)
}
extern "C" {
    pub static __BOOL_VTABLE: __RegisterVTable;
}
impl<'eval> __Register<'eval> {
    pub fn downcast_bool(&self) -> bool {
        unsafe {
            // println!("self.vtable.typename_str: {:?}", unsafe {
            //     std::ffi::CStr::from_ptr(self.vtable.typename_str)
            // });
            // println!("self.data_kind {:?}", self.data_kind());
            // println!(
            //     "self.vtable as *const _ == &__VOID_VTABLE as *const _ is {}",
            //     unsafe { self.vtable as *const _ == &__VOID_VTABLE as *const _ }
            // );
            assert_eq!(self.vtable as *const _, &__BOOL_VTABLE as *const _);
            match self.data_kind {
                __RegisterDataKind::PrimitiveValue => self.data.as_bool,
                _ => *(self.data.as_ptr as *const bool),
            }
        }
    }
}

// i32
#[no_mangle]
pub unsafe extern "C" fn __i32_primitive_value_to_bool(data: __RegisterData) -> bool {
    let data = data.as_i32;
    data != 0
}
#[no_mangle]
pub unsafe extern "C" fn __i32_primitive_value_to_box(data: __RegisterData) -> *mut () {
    let data = data.as_i32;
    let ptr: *mut i32 = Box::<i32>::into_raw(Box::new(data));
    ptr as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __i32_clone(data: *mut ()) -> *mut () {
    Box::<i32>::into_raw(Box::new((*(data as *mut i32)).clone())) as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __i32_drop(data: *mut ()) {
    Box::from_raw(data as *mut i32);
}
#[no_mangle]
pub unsafe extern "C" fn __i32_eq(this: &(), other: &()) -> bool {
    *(this as *const () as *const i32) == *(other as *const () as *const i32)
}
extern "C" {
    pub static __I32_VTABLE: __RegisterVTable;
}
impl<'eval> __Register<'eval> {
    pub fn downcast_i32(&self) -> i32 {
        unsafe {
            assert_eq!(self.vtable as *const _, &__I32_VTABLE as *const _);
            match self.data_kind {
                __RegisterDataKind::PrimitiveValue => self.data.as_i32,
                _ => *(self.data.as_ptr as *const i32),
            }
        }
    }
}

// i64
#[no_mangle]
pub unsafe extern "C" fn __i64_primitive_value_to_bool(data: __RegisterData) -> bool {
    let data = data.as_i64;
    data != 0
}
#[no_mangle]
pub unsafe extern "C" fn __i64_primitive_value_to_box(data: __RegisterData) -> *mut () {
    let data = data.as_i64;
    let ptr: *mut i64 = Box::<i64>::into_raw(Box::new(data));
    ptr as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __i64_clone(data: *mut ()) -> *mut () {
    Box::<i64>::into_raw(Box::new((*(data as *mut i64)).clone())) as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __i64_drop(data: *mut ()) {
    Box::from_raw(data as *mut i64);
}
#[no_mangle]
pub unsafe extern "C" fn __i64_eq(this: &(), other: &()) -> bool {
    *(this as *const () as *const i64) == *(other as *const () as *const i64)
}
extern "C" {
    pub static __I64_VTABLE: __RegisterVTable;
}
impl<'eval> __Register<'eval> {
    pub fn downcast_i64(&self) -> i64 {
        unsafe {
            assert_eq!(self.vtable as *const _, &__I64_VTABLE as *const _);
            match self.data_kind {
                __RegisterDataKind::PrimitiveValue => self.data.as_i64,
                _ => *(self.data.as_ptr as *const i64),
            }
        }
    }
}

// b32
#[no_mangle]
pub unsafe extern "C" fn __b32_primitive_value_to_bool(data: __RegisterData) -> bool {
    let data = data.as_b32;
    data != 0
}
#[no_mangle]
pub unsafe extern "C" fn __b32_primitive_value_to_box(data: __RegisterData) -> *mut () {
    let data = data.as_b32;
    let ptr: *mut b32 = Box::<b32>::into_raw(Box::new(data));
    ptr as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __b32_clone(data: *mut ()) -> *mut () {
    Box::<b32>::into_raw(Box::new((*(data as *mut b32)).clone())) as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __b32_drop(data: *mut ()) {
    Box::from_raw(data as *mut b32);
}
#[no_mangle]
pub unsafe extern "C" fn __b32_eq(this: &(), other: &()) -> bool {
    *(this as *const () as *const b32) == *(other as *const () as *const b32)
}
extern "C" {
    pub static __B32_VTABLE: __RegisterVTable;
}
impl<'eval> __Register<'eval> {
    pub fn downcast_b32(&self) -> b32 {
        unsafe {
            assert_eq!(self.vtable as *const _, &__B32_VTABLE as *const _);
            match self.data_kind {
                __RegisterDataKind::PrimitiveValue => self.data.as_b32,
                _ => *(self.data.as_ptr as *const b32),
            }
        }
    }
}

// b64
#[no_mangle]
pub unsafe extern "C" fn __b64_primitive_value_to_bool(data: __RegisterData) -> bool {
    let data = data.as_b64;
    data != 0
}
#[no_mangle]
pub unsafe extern "C" fn __b64_primitive_value_to_box(data: __RegisterData) -> *mut () {
    let data = data.as_b64;
    let ptr: *mut b64 = Box::<b64>::into_raw(Box::new(data));
    ptr as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __b64_clone(data: *mut ()) -> *mut () {
    Box::<b64>::into_raw(Box::new((*(data as *mut b64)).clone())) as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __b64_drop(data: *mut ()) {
    Box::from_raw(data as *mut b64);
}
#[no_mangle]
pub unsafe extern "C" fn __b64_eq(this: &(), other: &()) -> bool {
    *(this as *const () as *const b64) == *(other as *const () as *const b64)
}
extern "C" {
    pub static __B64_VTABLE: __RegisterVTable;
}
impl<'eval> __Register<'eval> {
    pub fn downcast_b64(&self) -> b64 {
        unsafe {
            assert_eq!(self.vtable as *const _, &__B64_VTABLE as *const _);
            match self.data_kind {
                __RegisterDataKind::PrimitiveValue => self.data.as_b64,
                _ => *(self.data.as_ptr as *const b64),
            }
        }
    }
}

// f32
#[no_mangle]
pub unsafe extern "C" fn __f32_primitive_value_to_bool(data: __RegisterData) -> bool {
    let data = data.as_f32;
    data != 0.0
}
#[no_mangle]
pub unsafe extern "C" fn __f32_primitive_value_to_box(data: __RegisterData) -> *mut () {
    let data = data.as_f32;
    let ptr: *mut f32 = Box::<f32>::into_raw(Box::new(data));
    ptr as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __f32_clone(data: *mut ()) -> *mut () {
    Box::<f32>::into_raw(Box::new((*(data as *mut f32)).clone())) as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __f32_drop(data: *mut ()) {
    Box::from_raw(data as *mut f32);
}
#[no_mangle]
pub unsafe extern "C" fn __f32_eq(this: &(), other: &()) -> bool {
    *(this as *const () as *const f32) == *(other as *const () as *const f32)
}
extern "C" {
    pub static __F32_VTABLE: __RegisterVTable;
}
impl<'eval> __Register<'eval> {
    pub fn downcast_f32(&self) -> f32 {
        unsafe {
            assert_eq!(self.vtable as *const _, &__F32_VTABLE as *const _);
            match self.data_kind {
                __RegisterDataKind::PrimitiveValue => self.data.as_f32,
                _ => *(self.data.as_ptr as *const f32),
            }
        }
    }
}

// f64
#[no_mangle]
pub unsafe extern "C" fn __f64_primitive_value_to_bool(data: __RegisterData) -> bool {
    let data = data.as_f64;
    data != 0.0
}
#[no_mangle]
pub unsafe extern "C" fn __f64_primitive_value_to_box(data: __RegisterData) -> *mut () {
    let data = data.as_f64;
    let ptr: *mut f64 = Box::<f64>::into_raw(Box::new(data));
    ptr as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __f64_clone(data: *mut ()) -> *mut () {
    Box::<f64>::into_raw(Box::new((*(data as *mut f64)).clone())) as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __f64_drop(data: *mut ()) {
    Box::from_raw(data as *mut f64);
}
#[no_mangle]
pub unsafe extern "C" fn __f64_eq(this: &(), other: &()) -> bool {
    *(this as *const () as *const f64) == *(other as *const () as *const f64)
}
extern "C" {
    pub static __F64_VTABLE: __RegisterVTable;
}
impl<'eval> __Register<'eval> {
    pub fn downcast_f64(&self) -> f64 {
        unsafe {
            assert_eq!(self.vtable as *const _, &__F64_VTABLE as *const _);
            match self.data_kind {
                __RegisterDataKind::PrimitiveValue => self.data.as_f64,
                _ => *(self.data.as_ptr as *const f64),
            }
        }
    }
}

// __VirtualFunction
#[no_mangle]
pub unsafe extern "C" fn __virtual_function_clone(data: *mut ()) -> *mut () {
    Box::<__VirtualFunction>::into_raw(Box::new((*(data as *mut __VirtualFunction)).clone()))
        as *mut ()
}
#[no_mangle]
pub unsafe extern "C" fn __virtual_function_drop(data: *mut ()) {
    Box::from_raw(data as *mut __VirtualFunction);
}
#[no_mangle]
pub unsafe extern "C" fn __virtual_function_eq(this: &(), other: &()) -> bool {
    *(this as *const () as *const __VirtualFunction)
        == *(other as *const () as *const __VirtualFunction)
}
extern "C" {
    pub static __VIRTUAL_FUNCTION_VTABLE: __RegisterVTable;
}
