#[repr(u8)]
pub enum TexMathLetter {
    UpperA,
    UpperB,
    UpperC,
    UpperD,
    UpperE,
    UpperF,
    UpperG,
    UpperH,
    UpperI,
    UpperJ,
    UpperK,
    UpperL,
    UpperM,
    UpperN,
    UpperO,
    UpperP,
    UpperQ,
    UpperR,
    UpperS,
    UpperT,
    UpperU,
    UpperV,
    UpperW,
    UpperX,
    UpperY,
    UpperZ,
    LowerA,
    LowerB,
    LowerC,
    LowerD,
    LowerE,
    LowerF,
    LowerG,
    LowerH,
    LowerI,
    LowerJ,
    LowerK,
    LowerL,
    LowerM,
    LowerN,
    LowerO,
    LowerP,
    LowerQ,
    LowerR,
    LowerS,
    LowerT,
    LowerU,
    LowerV,
    LowerW,
    LowerX,
    LowerY,
    LowerZ,
    MathcalA,
    MathcalB,
    MathcalC,
    MathcalD,
    MathcalE,
    MathcalF,
    MathcalG,
    MathcalH,
    MathcalI,
    MathcalJ,
    MathcalK,
    MathcalL,
    MathcalM,
    MathcalN,
    MathcalO,
    MathcalP,
    MathcalQ,
    MathcalR,
    MathcalS,
    MathcalT,
    MathcalU,
    MathcalV,
    MathcalW,
    MathcalX,
    MathcalY,
    MathcalZ,
    MathbbA,
    MathbbB,
    MathbbC,
    MathbbD,
    MathbbE,
    MathbbF,
    MathbbG,
    MathbbH,
    MathbbI,
    MathbbJ,
    MathbbK,
    MathbbL,
    MathbbM,
    MathbbN,
    MathbbO,
    MathbbP,
    MathbbQ,
    MathbbR,
    MathbbS,
    MathbbT,
    MathbbU,
    MathbbV,
    MathbbW,
    MathbbX,
    MathbbY,
    MathbbZ,
    MathfrakA,
    MathfrakB,
    MathfrakC,
    MathfrakD,
    MathfrakE,
    MathfrakF,
    MathfrakG,
    MathfrakH,
    MathfrakI,
    MathfrakJ,
    MathfrakK,
    MathfrakL,
    MathfrakM,
    MathfrakN,
    MathfrakO,
    MathfrakP,
    MathfrakQ,
    MathfrakR,
    MathfrakS,
    MathfrakT,
    MathfrakU,
    MathfrakV,
    MathfrakW,
    MathfrakX,
    MathfrakY,
    MathfrakZ,
    UpperGamma,
    UpperDelta,
    UpperTheta,
    UpperLambda,
    UpperXi,
    UpperPi,
    UpperSigma,
    UpperPhi,
    UpperPsi,
    UpperOmega,
    LowerAlpha,
    LowerBeta,
    LowerGamma,
    LowerDelta,
    LowerEpsilon,
    LowerZeta,
    LowerEta,
    LowerTheta,
    LowerIota,
    LowerKappa,
    LowerLambda,
    LowerMu,
    LowerNu,
    LowerXi,
    LowerOmicron,
    LowerPi,
    LowerRho,
    LowerSigma,
    LowerTau,
    LowerUpsilon,
    LowerPhi,
    LowerChi,
    LowerPsi,
    LowerOmega,
}

impl TexMathLetter {
    pub fn tex(self) -> &'static str {
        match self {
            TexMathLetter::UpperA => "A",
            TexMathLetter::UpperB => "B",
            TexMathLetter::UpperC => "C",
            TexMathLetter::UpperD => "D",
            TexMathLetter::UpperE => "E",
            TexMathLetter::UpperF => "F",
            TexMathLetter::UpperG => "G",
            TexMathLetter::UpperH => "H",
            TexMathLetter::UpperI => "I",
            TexMathLetter::UpperJ => "J",
            TexMathLetter::UpperK => "K",
            TexMathLetter::UpperL => "L",
            TexMathLetter::UpperM => "M",
            TexMathLetter::UpperN => "N",
            TexMathLetter::UpperO => "O",
            TexMathLetter::UpperP => "P",
            TexMathLetter::UpperQ => "Q",
            TexMathLetter::UpperR => "R",
            TexMathLetter::UpperS => "S",
            TexMathLetter::UpperT => "T",
            TexMathLetter::UpperU => "U",
            TexMathLetter::UpperV => "V",
            TexMathLetter::UpperW => "W",
            TexMathLetter::UpperX => "X",
            TexMathLetter::UpperY => "Y",
            TexMathLetter::UpperZ => "Z",
            TexMathLetter::LowerA => "a",
            TexMathLetter::LowerB => "b",
            TexMathLetter::LowerC => "c",
            TexMathLetter::LowerD => "d",
            TexMathLetter::LowerE => "e",
            TexMathLetter::LowerF => "f",
            TexMathLetter::LowerG => "g",
            TexMathLetter::LowerH => "h",
            TexMathLetter::LowerI => "i",
            TexMathLetter::LowerJ => "j",
            TexMathLetter::LowerK => "k",
            TexMathLetter::LowerL => "l",
            TexMathLetter::LowerM => "m",
            TexMathLetter::LowerN => "n",
            TexMathLetter::LowerO => "o",
            TexMathLetter::LowerP => "p",
            TexMathLetter::LowerQ => "q",
            TexMathLetter::LowerR => "r",
            TexMathLetter::LowerS => "s",
            TexMathLetter::LowerT => "t",
            TexMathLetter::LowerU => "u",
            TexMathLetter::LowerV => "v",
            TexMathLetter::LowerW => "w",
            TexMathLetter::LowerX => "x",
            TexMathLetter::LowerY => "y",
            TexMathLetter::LowerZ => "z",
            TexMathLetter::MathcalA => "\\mathcal{A}",
            TexMathLetter::MathcalB => "\\mathcal{B}",
            TexMathLetter::MathcalC => "\\mathcal{C}",
            TexMathLetter::MathcalD => "\\mathcal{D}",
            TexMathLetter::MathcalE => "\\mathcal{E}",
            TexMathLetter::MathcalF => "\\mathcal{F}",
            TexMathLetter::MathcalG => "\\mathcal{G}",
            TexMathLetter::MathcalH => "\\mathcal{H}",
            TexMathLetter::MathcalI => "\\mathcal{I}",
            TexMathLetter::MathcalJ => "\\mathcal{J}",
            TexMathLetter::MathcalK => "\\mathcal{K}",
            TexMathLetter::MathcalL => "\\mathcal{L}",
            TexMathLetter::MathcalM => "\\mathcal{M}",
            TexMathLetter::MathcalN => "\\mathcal{N}",
            TexMathLetter::MathcalO => "\\mathcal{O}",
            TexMathLetter::MathcalP => "\\mathcal{P}",
            TexMathLetter::MathcalQ => "\\mathcal{Q}",
            TexMathLetter::MathcalR => "\\mathcal{R}",
            TexMathLetter::MathcalS => "\\mathcal{S}",
            TexMathLetter::MathcalT => "\\mathcal{T}",
            TexMathLetter::MathcalU => "\\mathcal{U}",
            TexMathLetter::MathcalV => "\\mathcal{V}",
            TexMathLetter::MathcalW => "\\mathcal{W}",
            TexMathLetter::MathcalX => "\\mathcal{X}",
            TexMathLetter::MathcalY => "\\mathcal{Y}",
            TexMathLetter::MathcalZ => "\\mathcal{Z}",
            TexMathLetter::MathbbA => "\\mathbb{A}",
            TexMathLetter::MathbbB => "\\mathbb{B}",
            TexMathLetter::MathbbC => "\\mathbb{C}",
            TexMathLetter::MathbbD => "\\mathbb{D}",
            TexMathLetter::MathbbE => "\\mathbb{E}",
            TexMathLetter::MathbbF => "\\mathbb{F}",
            TexMathLetter::MathbbG => "\\mathbb{G}",
            TexMathLetter::MathbbH => "\\mathbb{H}",
            TexMathLetter::MathbbI => "\\mathbb{I}",
            TexMathLetter::MathbbJ => "\\mathbb{J}",
            TexMathLetter::MathbbK => "\\mathbb{K}",
            TexMathLetter::MathbbL => "\\mathbb{L}",
            TexMathLetter::MathbbM => "\\mathbb{M}",
            TexMathLetter::MathbbN => "\\mathbb{N}",
            TexMathLetter::MathbbO => "\\mathbb{O}",
            TexMathLetter::MathbbP => "\\mathbb{P}",
            TexMathLetter::MathbbQ => "\\mathbb{Q}",
            TexMathLetter::MathbbR => "\\mathbb{R}",
            TexMathLetter::MathbbS => "\\mathbb{S}",
            TexMathLetter::MathbbT => "\\mathbb{T}",
            TexMathLetter::MathbbU => "\\mathbb{U}",
            TexMathLetter::MathbbV => "\\mathbb{V}",
            TexMathLetter::MathbbW => "\\mathbb{W}",
            TexMathLetter::MathbbX => "\\mathbb{X}",
            TexMathLetter::MathbbY => "\\mathbb{Y}",
            TexMathLetter::MathbbZ => "\\mathbb{Z}",
            TexMathLetter::MathfrakA => "\\mathfrak{A}",
            TexMathLetter::MathfrakB => "\\mathfrak{B}",
            TexMathLetter::MathfrakC => "\\mathfrak{C}",
            TexMathLetter::MathfrakD => "\\mathfrak{D}",
            TexMathLetter::MathfrakE => "\\mathfrak{E}",
            TexMathLetter::MathfrakF => "\\mathfrak{F}",
            TexMathLetter::MathfrakG => "\\mathfrak{G}",
            TexMathLetter::MathfrakH => "\\mathfrak{H}",
            TexMathLetter::MathfrakI => "\\mathfrak{I}",
            TexMathLetter::MathfrakJ => "\\mathfrak{J}",
            TexMathLetter::MathfrakK => "\\mathfrak{K}",
            TexMathLetter::MathfrakL => "\\mathfrak{L}",
            TexMathLetter::MathfrakM => "\\mathfrak{M}",
            TexMathLetter::MathfrakN => "\\mathfrak{N}",
            TexMathLetter::MathfrakO => "\\mathfrak{O}",
            TexMathLetter::MathfrakP => "\\mathfrak{P}",
            TexMathLetter::MathfrakQ => "\\mathfrak{Q}",
            TexMathLetter::MathfrakR => "\\mathfrak{R}",
            TexMathLetter::MathfrakS => "\\mathfrak{S}",
            TexMathLetter::MathfrakT => "\\mathfrak{T}",
            TexMathLetter::MathfrakU => "\\mathfrak{U}",
            TexMathLetter::MathfrakV => "\\mathfrak{V}",
            TexMathLetter::MathfrakW => "\\mathfrak{W}",
            TexMathLetter::MathfrakX => "\\mathfrak{X}",
            TexMathLetter::MathfrakY => "\\mathfrak{Y}",
            TexMathLetter::MathfrakZ => "\\mathfrak{Z}",
            TexMathLetter::UpperGamma => "\\Gamma",
            TexMathLetter::UpperDelta => "\\Delta",
            TexMathLetter::UpperTheta => "\\Theta",
            TexMathLetter::UpperLambda => "\\Lambda",
            TexMathLetter::UpperXi => "\\Xi",
            TexMathLetter::UpperPi => "\\Pi",
            TexMathLetter::UpperSigma => "\\Sigma",
            TexMathLetter::UpperPhi => "\\Phi",
            TexMathLetter::UpperPsi => "\\Psi",
            TexMathLetter::UpperOmega => "\\Omega",
            TexMathLetter::LowerAlpha => "\\alpha",
            TexMathLetter::LowerBeta => "\\beta",
            TexMathLetter::LowerGamma => "\\gamma",
            TexMathLetter::LowerDelta => "\\delta",
            TexMathLetter::LowerEpsilon => "\\epsilon",
            TexMathLetter::LowerZeta => "\\zeta",
            TexMathLetter::LowerEta => "\\eta",
            TexMathLetter::LowerTheta => "\\theta",
            TexMathLetter::LowerIota => "\\iota",
            TexMathLetter::LowerKappa => "\\kappa",
            TexMathLetter::LowerLambda => "\\lambda",
            TexMathLetter::LowerMu => "\\mu",
            TexMathLetter::LowerNu => "\\nu",
            TexMathLetter::LowerXi => "\\xi",
            TexMathLetter::LowerOmicron => "o", // No special LaTeX command for omicron
            TexMathLetter::LowerPi => "\\pi",
            TexMathLetter::LowerRho => "\\rho",
            TexMathLetter::LowerSigma => "\\sigma",
            TexMathLetter::LowerTau => "\\tau",
            TexMathLetter::LowerUpsilon => "\\upsilon",
            TexMathLetter::LowerPhi => "\\phi",
            TexMathLetter::LowerChi => "\\chi",
            TexMathLetter::LowerPsi => "\\psi",
            TexMathLetter::LowerOmega => "\\omega",
        }
    }

    pub fn try_from_char(c: char) -> Option<Self> {
        Some(match c {
            'A' => TexMathLetter::UpperA,
            'B' => TexMathLetter::UpperB,
            'C' => TexMathLetter::UpperC,
            'D' => TexMathLetter::UpperD,
            'E' => TexMathLetter::UpperE,
            'F' => TexMathLetter::UpperF,
            'G' => TexMathLetter::UpperG,
            'H' => TexMathLetter::UpperH,
            'I' => TexMathLetter::UpperI,
            'J' => TexMathLetter::UpperJ,
            'K' => TexMathLetter::UpperK,
            'L' => TexMathLetter::UpperL,
            'M' => TexMathLetter::UpperM,
            'N' => TexMathLetter::UpperN,
            'O' => TexMathLetter::UpperO,
            'P' => TexMathLetter::UpperP,
            'Q' => TexMathLetter::UpperQ,
            'R' => TexMathLetter::UpperR,
            'S' => TexMathLetter::UpperS,
            'T' => TexMathLetter::UpperT,
            'U' => TexMathLetter::UpperU,
            'V' => TexMathLetter::UpperV,
            'W' => TexMathLetter::UpperW,
            'X' => TexMathLetter::UpperX,
            'Y' => TexMathLetter::UpperY,
            'Z' => TexMathLetter::UpperZ,
            'a' => TexMathLetter::LowerA,
            'b' => TexMathLetter::LowerB,
            'c' => TexMathLetter::LowerC,
            'd' => TexMathLetter::LowerD,
            'e' => TexMathLetter::LowerE,
            'f' => TexMathLetter::LowerF,
            'g' => TexMathLetter::LowerG,
            'h' => TexMathLetter::LowerH,
            'i' => TexMathLetter::LowerI,
            'j' => TexMathLetter::LowerJ,
            'k' => TexMathLetter::LowerK,
            'l' => TexMathLetter::LowerL,
            'm' => TexMathLetter::LowerM,
            'n' => TexMathLetter::LowerN,
            'o' => TexMathLetter::LowerO,
            'p' => TexMathLetter::LowerP,
            'q' => TexMathLetter::LowerQ,
            'r' => TexMathLetter::LowerR,
            's' => TexMathLetter::LowerS,
            't' => TexMathLetter::LowerT,
            'u' => TexMathLetter::LowerU,
            'v' => TexMathLetter::LowerV,
            'w' => TexMathLetter::LowerW,
            'x' => TexMathLetter::LowerX,
            'y' => TexMathLetter::LowerY,
            'z' => TexMathLetter::LowerZ,
            'Γ' => TexMathLetter::UpperGamma,
            'Δ' => TexMathLetter::UpperDelta,
            'Θ' => TexMathLetter::UpperTheta,
            'Λ' => TexMathLetter::UpperLambda,
            'Ξ' => TexMathLetter::UpperXi,
            'Π' => TexMathLetter::UpperPi,
            'Σ' => TexMathLetter::UpperSigma,
            'Φ' => TexMathLetter::UpperPhi,
            'Ψ' => TexMathLetter::UpperPsi,
            'Ω' => TexMathLetter::UpperOmega,
            'α' => TexMathLetter::LowerAlpha,
            'β' => TexMathLetter::LowerBeta,
            'γ' => TexMathLetter::LowerGamma,
            'δ' => TexMathLetter::LowerDelta,
            'ε' => TexMathLetter::LowerEpsilon,
            'ζ' => TexMathLetter::LowerZeta,
            'η' => TexMathLetter::LowerEta,
            'θ' => TexMathLetter::LowerTheta,
            'ι' => TexMathLetter::LowerIota,
            'κ' => TexMathLetter::LowerKappa,
            'λ' => TexMathLetter::LowerLambda,
            'μ' => TexMathLetter::LowerMu,
            'ν' => TexMathLetter::LowerNu,
            'ξ' => TexMathLetter::LowerXi,
            'ο' => TexMathLetter::LowerOmicron,
            'π' => TexMathLetter::LowerPi,
            'ρ' => TexMathLetter::LowerRho,
            'σ' => TexMathLetter::LowerSigma,
            'τ' => TexMathLetter::LowerTau,
            'υ' => TexMathLetter::LowerUpsilon,
            'φ' => TexMathLetter::LowerPhi,
            'χ' => TexMathLetter::LowerChi,
            'ψ' => TexMathLetter::LowerPsi,
            'ω' => TexMathLetter::LowerOmega,
            _ => return None,
        })
    }
}

impl TexMathLetter {
    pub fn to_char(self) -> char {
        match self {
            TexMathLetter::UpperA => 'A',
            TexMathLetter::UpperB => 'B',
            TexMathLetter::UpperC => 'C',
            TexMathLetter::UpperD => 'D',
            TexMathLetter::UpperE => 'E',
            TexMathLetter::UpperF => 'F',
            TexMathLetter::UpperG => 'G',
            TexMathLetter::UpperH => 'H',
            TexMathLetter::UpperI => 'I',
            TexMathLetter::UpperJ => 'J',
            TexMathLetter::UpperK => 'K',
            TexMathLetter::UpperL => 'L',
            TexMathLetter::UpperM => 'M',
            TexMathLetter::UpperN => 'N',
            TexMathLetter::UpperO => 'O',
            TexMathLetter::UpperP => 'P',
            TexMathLetter::UpperQ => 'Q',
            TexMathLetter::UpperR => 'R',
            TexMathLetter::UpperS => 'S',
            TexMathLetter::UpperT => 'T',
            TexMathLetter::UpperU => 'U',
            TexMathLetter::UpperV => 'V',
            TexMathLetter::UpperW => 'W',
            TexMathLetter::UpperX => 'X',
            TexMathLetter::UpperY => 'Y',
            TexMathLetter::UpperZ => 'Z',
            TexMathLetter::LowerA => 'a',
            TexMathLetter::LowerB => 'b',
            TexMathLetter::LowerC => 'c',
            TexMathLetter::LowerD => 'd',
            TexMathLetter::LowerE => 'e',
            TexMathLetter::LowerF => 'f',
            TexMathLetter::LowerG => 'g',
            TexMathLetter::LowerH => 'h',
            TexMathLetter::LowerI => 'i',
            TexMathLetter::LowerJ => 'j',
            TexMathLetter::LowerK => 'k',
            TexMathLetter::LowerL => 'l',
            TexMathLetter::LowerM => 'm',
            TexMathLetter::LowerN => 'n',
            TexMathLetter::LowerO => 'o',
            TexMathLetter::LowerP => 'p',
            TexMathLetter::LowerQ => 'q',
            TexMathLetter::LowerR => 'r',
            TexMathLetter::LowerS => 's',
            TexMathLetter::LowerT => 't',
            TexMathLetter::LowerU => 'u',
            TexMathLetter::LowerV => 'v',
            TexMathLetter::LowerW => 'w',
            TexMathLetter::LowerX => 'x',
            TexMathLetter::LowerY => 'y',
            TexMathLetter::LowerZ => 'z',
            TexMathLetter::MathcalA => 'A',
            TexMathLetter::MathcalB => 'B',
            TexMathLetter::MathcalC => 'C',
            TexMathLetter::MathcalD => 'D',
            TexMathLetter::MathcalE => 'E',
            TexMathLetter::MathcalF => 'F',
            TexMathLetter::MathcalG => 'G',
            TexMathLetter::MathcalH => 'H',
            TexMathLetter::MathcalI => 'I',
            TexMathLetter::MathcalJ => 'J',
            TexMathLetter::MathcalK => 'K',
            TexMathLetter::MathcalL => 'L',
            TexMathLetter::MathcalM => 'M',
            TexMathLetter::MathcalN => 'N',
            TexMathLetter::MathcalO => 'O',
            TexMathLetter::MathcalP => 'P',
            TexMathLetter::MathcalQ => 'Q',
            TexMathLetter::MathcalR => 'R',
            TexMathLetter::MathcalS => 'S',
            TexMathLetter::MathcalT => 'T',
            TexMathLetter::MathcalU => 'U',
            TexMathLetter::MathcalV => 'V',
            TexMathLetter::MathcalW => 'W',
            TexMathLetter::MathcalX => 'X',
            TexMathLetter::MathcalY => 'Y',
            TexMathLetter::MathcalZ => 'Z',
            TexMathLetter::MathbbA => 'A',
            TexMathLetter::MathbbB => 'B',
            TexMathLetter::MathbbC => 'C',
            TexMathLetter::MathbbD => 'D',
            TexMathLetter::MathbbE => 'E',
            TexMathLetter::MathbbF => 'F',
            TexMathLetter::MathbbG => 'G',
            TexMathLetter::MathbbH => 'H',
            TexMathLetter::MathbbI => 'I',
            TexMathLetter::MathbbJ => 'J',
            TexMathLetter::MathbbK => 'K',
            TexMathLetter::MathbbL => 'L',
            TexMathLetter::MathbbM => 'M',
            TexMathLetter::MathbbN => 'N',
            TexMathLetter::MathbbO => 'O',
            TexMathLetter::MathbbP => 'P',
            TexMathLetter::MathbbQ => 'Q',
            TexMathLetter::MathbbR => 'R',
            TexMathLetter::MathbbS => 'S',
            TexMathLetter::MathbbT => 'T',
            TexMathLetter::MathbbU => 'U',
            TexMathLetter::MathbbV => 'V',
            TexMathLetter::MathbbW => 'W',
            TexMathLetter::MathbbX => 'X',
            TexMathLetter::MathbbY => 'Y',
            TexMathLetter::MathbbZ => 'Z',
            TexMathLetter::MathfrakA => 'a',
            TexMathLetter::MathfrakB => 'b',
            TexMathLetter::MathfrakC => 'c',
            TexMathLetter::MathfrakD => 'd',
            TexMathLetter::MathfrakE => 'e',
            TexMathLetter::MathfrakF => 'f',
            TexMathLetter::MathfrakG => 'g',
            TexMathLetter::MathfrakH => 'h',
            TexMathLetter::MathfrakI => 'i',
            TexMathLetter::MathfrakJ => 'j',
            TexMathLetter::MathfrakK => 'k',
            TexMathLetter::MathfrakL => 'l',
            TexMathLetter::MathfrakM => 'm',
            TexMathLetter::MathfrakN => 'n',
            TexMathLetter::MathfrakO => 'o',
            TexMathLetter::MathfrakP => 'p',
            TexMathLetter::MathfrakQ => 'q',
            TexMathLetter::MathfrakR => 'r',
            TexMathLetter::MathfrakS => 's',
            TexMathLetter::MathfrakT => 't',
            TexMathLetter::MathfrakU => 'u',
            TexMathLetter::MathfrakV => 'v',
            TexMathLetter::MathfrakW => 'w',
            TexMathLetter::MathfrakX => 'x',
            TexMathLetter::MathfrakY => 'y',
            TexMathLetter::MathfrakZ => 'z',
            TexMathLetter::UpperGamma => 'Γ',
            TexMathLetter::UpperDelta => 'Δ',
            TexMathLetter::UpperTheta => 'Θ',
            TexMathLetter::UpperLambda => 'Λ',
            TexMathLetter::UpperXi => 'Ξ',
            TexMathLetter::UpperPi => 'Π',
            TexMathLetter::UpperSigma => 'Σ',
            TexMathLetter::UpperPhi => 'Φ',
            TexMathLetter::UpperPsi => 'Ψ',
            TexMathLetter::UpperOmega => 'Ω',
            TexMathLetter::LowerAlpha => 'α',
            TexMathLetter::LowerBeta => 'β',
            TexMathLetter::LowerGamma => 'γ',
            TexMathLetter::LowerDelta => 'δ',
            TexMathLetter::LowerEpsilon => 'ε',
            TexMathLetter::LowerZeta => 'ζ',
            TexMathLetter::LowerEta => 'η',
            TexMathLetter::LowerTheta => 'θ',
            TexMathLetter::LowerIota => 'ι',
            TexMathLetter::LowerKappa => 'κ',
            TexMathLetter::LowerLambda => 'λ',
            TexMathLetter::LowerMu => 'μ',
            TexMathLetter::LowerNu => 'ν',
            TexMathLetter::LowerXi => 'ξ',
            TexMathLetter::LowerOmicron => 'ο',
            TexMathLetter::LowerPi => 'π',
            TexMathLetter::LowerRho => 'ρ',
            TexMathLetter::LowerSigma => 'σ',
            TexMathLetter::LowerTau => 'τ',
            TexMathLetter::LowerUpsilon => 'υ',
            TexMathLetter::LowerPhi => 'φ',
            TexMathLetter::LowerChi => 'χ',
            TexMathLetter::LowerPsi => 'ψ',
            TexMathLetter::LowerOmega => 'ω',
        }
    }
}
